/*重置算法配置，非registration融合算法均设置为need_gpu_processor＝1，*/
/*适用linkone所有版本*/
update alg set need_gpu_processor='1' where need_gpu_processor=0 and alias!='registration';
UPDATE `alg` SET `name`='Cerebrum', `alias`='head_segment_get_cerebrum_contours', `exec_file`='get_cerebrum_contours.py' WHERE `alias`='head_neck_segment_get_brain_contours';
UPDATE `alg` SET  `type_id`='11', `name`='Aorta' WHERE `alias`='chest_segment_get_adescendens_contours';

INSERT INTO `alg` (`type_id`, `kind_name`, `name`, `alias`, `docker_image`, `description`, `exec_file`, `output_filenames`, `need_gpu_processor`, `is_priority`, `cpu_limit`, `gpu_limit`, `memory_limit`, `status`, `created`, `updated`) VALUES ('1', 'segment', 'SMG', 'head_get_smg_contours', 'hub.linkingmed.com/centos_python_segment:1.2.0', '', 'get_SMG_contours.py', '', '1', '0', '0', '1', '0', '0', '0', '0');
INSERT INTO `alg` (`type_id`, `kind_name`, `name`, `alias`, `docker_image`, `description`, `exec_file`, `output_filenames`, `need_gpu_processor`, `is_priority`, `cpu_limit`, `gpu_limit`, `memory_limit`, `status`, `created`, `updated`) VALUES ('1', 'segment', 'OralCavity', 'head_get_oral_contours', 'hub.linkingmed.com/centos_python_segment:1.2.0', '', 'get_oral_contours.py', '', '1', '0', '0', '1', '0', '0', '0', '0');
INSERT INTO `alg` (`type_id`, `kind_name`, `name`, `alias`, `docker_image`, `description`, `exec_file`, `output_filenames`, `need_gpu_processor`, `is_priority`, `cpu_limit`, `gpu_limit`, `memory_limit`, `status`, `created`, `updated`) VALUES ('3', 'segment', 'Subclavian', 'chest_get_subclavian_contours', 'hub.linkingmed.com/centos_python_segment:1.2.0', '', 'get_subclavian_contours.py', '', '1', '0', '0', '1', '0', '0', '0', '0');
INSERT INTO `alg` (`type_id`, `kind_name`, `name`, `alias`, `docker_image`, `description`, `exec_file`, `output_filenames`, `need_gpu_processor`, `is_priority`, `cpu_limit`, `gpu_limit`, `memory_limit`, `status`, `created`, `updated`) VALUES ('11', 'segment', 'Vertebral', 'up_body_get_vertebral_contours', 'hub.linkingmed.com/centos_python_segment:1.2.0', '', 'get_Vertebral.A_contours.py', '', '1', '0', '0', '1', '0', '0', '0', '0');
INSERT INTO `alg` (`type_id`, `kind_name`, `name`, `alias`, `docker_image`, `description`, `exec_file`, `output_filenames`, `need_gpu_processor`, `is_priority`, `cpu_limit`, `gpu_limit`, `memory_limit`, `status`, `created`, `updated`) VALUES ('3', 'segment', 'IMA', 'chest_get_ima_contours', 'hub.linkingmed.com/centos_python_segment:1.2.0', '', 'get_IMA_contours.py', '', '1', '0', '0', '1', '0', '0', '0', '0');
INSERT INTO `alg` (`type_id`, `kind_name`, `name`, `alias`, `docker_image`, `description`, `exec_file`, `output_filenames`, `need_gpu_processor`, `is_priority`, `cpu_limit`, `gpu_limit`, `memory_limit`, `status`, `created`, `updated`) VALUES ('3', 'segment', 'IVC', 'chest_get_ivc_contours', 'hub.linkingmed.com/centos_python_segment:1.2.0', '', 'get_IVC_contours.py', '', '1', '0', '0', '1', '0', '0', '0', '0');
INSERT INTO `alg` (`type_id`, `kind_name`, `name`, `alias`, `docker_image`, `description`, `exec_file`, `output_filenames`, `need_gpu_processor`, `is_priority`, `cpu_limit`, `gpu_limit`, `memory_limit`, `status`, `created`, `updated`) VALUES ('1', 'segment', 'Brain', 'head_get_brain_contours', 'hub.linkingmed.com/centos_python_segment:1.2.0', '', 'get_brain_contours.py', '', '1', '0', '0', '1', '0', '0', '0', '0');
